package net.lenni0451.rivet.backend.awt.utils;

import lombok.experimental.UtilityClass;
import net.lenni0451.rivet.input.keyboard.Key;
import net.lenni0451.rivet.input.keyboard.ModifierKey;
import net.lenni0451.rivet.input.mouse.MouseButton;
import net.lenni0451.rivet.input.mouse.MouseButtonEvent;

import javax.annotation.Nullable;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.EnumSet;
import java.util.Set;

@UtilityClass
public class AWTMapper {

    @Nullable
    public static net.lenni0451.rivet.input.keyboard.KeyEvent mapKeycode(final int keycode, final int modifier) {
        Key key = switch (keycode) {
            case KeyEvent.VK_ENTER -> Key.ENTER;
            case KeyEvent.VK_BACK_SPACE -> Key.BACKSPACE;
            case KeyEvent.VK_TAB -> Key.TAB;
            case KeyEvent.VK_CANCEL -> null;
            case KeyEvent.VK_CLEAR -> null;
            case KeyEvent.VK_SHIFT -> Key.LEFT_SHIFT;
            case KeyEvent.VK_CONTROL -> Key.LEFT_CONTROL;
            case KeyEvent.VK_ALT -> Key.LEFT_ALT;
            case KeyEvent.VK_PAUSE -> Key.PAUSE;
            case KeyEvent.VK_CAPS_LOCK -> Key.CAPS_LOCK;
            case KeyEvent.VK_ESCAPE -> Key.ESCAPE;
            case KeyEvent.VK_SPACE -> Key.SPACE;
            case KeyEvent.VK_PAGE_UP -> Key.PAGE_UP;
            case KeyEvent.VK_PAGE_DOWN -> Key.PAGE_DOWN;
            case KeyEvent.VK_END -> Key.END;
            case KeyEvent.VK_HOME -> Key.HOME;
            case KeyEvent.VK_LEFT -> Key.LEFT;
            case KeyEvent.VK_UP -> Key.UP;
            case KeyEvent.VK_RIGHT -> Key.RIGHT;
            case KeyEvent.VK_DOWN -> Key.DOWN;
            case KeyEvent.VK_COMMA -> Key.COMMA;
            case KeyEvent.VK_MINUS -> Key.MINUS;
            case KeyEvent.VK_PERIOD -> Key.PERIOD;
            case KeyEvent.VK_SLASH -> Key.SLASH;
            case KeyEvent.VK_0 -> Key.KB_0;
            case KeyEvent.VK_1 -> Key.KB_1;
            case KeyEvent.VK_2 -> Key.KB_2;
            case KeyEvent.VK_3 -> Key.KB_3;
            case KeyEvent.VK_4 -> Key.KB_4;
            case KeyEvent.VK_5 -> Key.KB_5;
            case KeyEvent.VK_6 -> Key.KB_6;
            case KeyEvent.VK_7 -> Key.KB_7;
            case KeyEvent.VK_8 -> Key.KB_8;
            case KeyEvent.VK_9 -> Key.KB_9;
            case KeyEvent.VK_SEMICOLON -> Key.SEMICOLON;
            case KeyEvent.VK_EQUALS -> Key.EQUAL;
            case KeyEvent.VK_A -> Key.A;
            case KeyEvent.VK_B -> Key.B;
            case KeyEvent.VK_C -> Key.C;
            case KeyEvent.VK_D -> Key.D;
            case KeyEvent.VK_E -> Key.E;
            case KeyEvent.VK_F -> Key.F;
            case KeyEvent.VK_G -> Key.G;
            case KeyEvent.VK_H -> Key.H;
            case KeyEvent.VK_I -> Key.I;
            case KeyEvent.VK_J -> Key.J;
            case KeyEvent.VK_K -> Key.K;
            case KeyEvent.VK_L -> Key.L;
            case KeyEvent.VK_M -> Key.M;
            case KeyEvent.VK_N -> Key.N;
            case KeyEvent.VK_O -> Key.O;
            case KeyEvent.VK_P -> Key.P;
            case KeyEvent.VK_Q -> Key.Q;
            case KeyEvent.VK_R -> Key.R;
            case KeyEvent.VK_S -> Key.S;
            case KeyEvent.VK_T -> Key.T;
            case KeyEvent.VK_U -> Key.U;
            case KeyEvent.VK_V -> Key.V;
            case KeyEvent.VK_W -> Key.W;
            case KeyEvent.VK_X -> Key.X;
            case KeyEvent.VK_Y -> Key.Y;
            case KeyEvent.VK_Z -> Key.Z;
            case KeyEvent.VK_OPEN_BRACKET -> Key.LEFT_BRACKET;
            case KeyEvent.VK_BACK_SLASH -> Key.BACKSLASH;
            case KeyEvent.VK_CLOSE_BRACKET -> Key.RIGHT_BRACKET;
            case KeyEvent.VK_NUMPAD0 -> Key.KP_0;
            case KeyEvent.VK_NUMPAD1 -> Key.KP_1;
            case KeyEvent.VK_NUMPAD2 -> Key.KP_2;
            case KeyEvent.VK_NUMPAD3 -> Key.KP_3;
            case KeyEvent.VK_NUMPAD4 -> Key.KP_4;
            case KeyEvent.VK_NUMPAD5 -> Key.KP_5;
            case KeyEvent.VK_NUMPAD6 -> Key.KP_6;
            case KeyEvent.VK_NUMPAD7 -> Key.KP_7;
            case KeyEvent.VK_NUMPAD8 -> Key.KP_8;
            case KeyEvent.VK_NUMPAD9 -> Key.KP_9;
            case KeyEvent.VK_MULTIPLY -> Key.KP_MULTIPLY;
            case KeyEvent.VK_ADD -> Key.KP_ADD;
            case KeyEvent.VK_SEPARATOR -> null;
            case KeyEvent.VK_SUBTRACT -> Key.KP_SUBTRACT;
            case KeyEvent.VK_DECIMAL -> Key.KP_DECIMAL;
            case KeyEvent.VK_DIVIDE -> Key.KP_DIVIDE;
            case KeyEvent.VK_DELETE -> Key.DELETE;
            case KeyEvent.VK_NUM_LOCK -> Key.NUM_LOCK;
            case KeyEvent.VK_SCROLL_LOCK -> Key.SCROLL_LOCK;
            case KeyEvent.VK_F1 -> Key.F1;
            case KeyEvent.VK_F2 -> Key.F2;
            case KeyEvent.VK_F3 -> Key.F3;
            case KeyEvent.VK_F4 -> Key.F4;
            case KeyEvent.VK_F5 -> Key.F5;
            case KeyEvent.VK_F6 -> Key.F6;
            case KeyEvent.VK_F7 -> Key.F7;
            case KeyEvent.VK_F8 -> Key.F8;
            case KeyEvent.VK_F9 -> Key.F9;
            case KeyEvent.VK_F10 -> Key.F10;
            case KeyEvent.VK_F11 -> Key.F11;
            case KeyEvent.VK_F12 -> Key.F12;
            case KeyEvent.VK_F13 -> Key.F13;
            case KeyEvent.VK_F14 -> Key.F14;
            case KeyEvent.VK_F15 -> Key.F15;
            case KeyEvent.VK_F16 -> Key.F16;
            case KeyEvent.VK_F17 -> Key.F17;
            case KeyEvent.VK_F18 -> Key.F18;
            case KeyEvent.VK_F19 -> Key.F19;
            case KeyEvent.VK_F20 -> Key.F20;
            case KeyEvent.VK_F21 -> Key.F21;
            case KeyEvent.VK_F22 -> Key.F22;
            case KeyEvent.VK_F23 -> Key.F23;
            case KeyEvent.VK_F24 -> Key.F24;
            case KeyEvent.VK_PRINTSCREEN -> Key.PRINT_SCREEN;
            case KeyEvent.VK_INSERT -> Key.INSERT;
            case KeyEvent.VK_HELP -> null;
            case KeyEvent.VK_META -> Key.LEFT_SUPER;
            case KeyEvent.VK_BACK_QUOTE -> Key.GRAVE_ACCENT;
            case KeyEvent.VK_QUOTE -> Key.APOSTROPHE;
            case KeyEvent.VK_KP_UP -> Key.UP;
            case KeyEvent.VK_KP_DOWN -> Key.DOWN;
            case KeyEvent.VK_KP_LEFT -> Key.LEFT;
            case KeyEvent.VK_KP_RIGHT -> Key.RIGHT;
            case KeyEvent.VK_DEAD_GRAVE -> null;
            case KeyEvent.VK_DEAD_ACUTE -> null;
            case KeyEvent.VK_DEAD_CIRCUMFLEX -> null;
            case KeyEvent.VK_DEAD_TILDE -> null;
            case KeyEvent.VK_DEAD_MACRON -> null;
            case KeyEvent.VK_DEAD_BREVE -> null;
            case KeyEvent.VK_DEAD_ABOVEDOT -> null;
            case KeyEvent.VK_DEAD_DIAERESIS -> null;
            case KeyEvent.VK_DEAD_ABOVERING -> null;
            case KeyEvent.VK_DEAD_DOUBLEACUTE -> null;
            case KeyEvent.VK_DEAD_CARON -> null;
            case KeyEvent.VK_DEAD_CEDILLA -> null;
            case KeyEvent.VK_DEAD_OGONEK -> null;
            case KeyEvent.VK_DEAD_IOTA -> null;
            case KeyEvent.VK_DEAD_VOICED_SOUND -> null;
            case KeyEvent.VK_DEAD_SEMIVOICED_SOUND -> null;
            case KeyEvent.VK_AMPERSAND -> Key.AMPERSAND;
            case KeyEvent.VK_ASTERISK -> Key.ASTERISK;
            case KeyEvent.VK_QUOTEDBL -> Key.DOUBLE_QUOTE;
            case KeyEvent.VK_LESS -> Key.LESS;
            case KeyEvent.VK_GREATER -> Key.GREATER;
            case KeyEvent.VK_BRACELEFT -> Key.LEFT_BRACE;
            case KeyEvent.VK_BRACERIGHT -> Key.RIGHT_BRACE;
            case KeyEvent.VK_AT -> Key.AT;
            case KeyEvent.VK_COLON -> Key.COLON;
            case KeyEvent.VK_CIRCUMFLEX -> Key.CARET;
            case KeyEvent.VK_DOLLAR -> Key.DOLLAR;
            case KeyEvent.VK_EURO_SIGN -> null;
            case KeyEvent.VK_EXCLAMATION_MARK -> Key.EXCLAMATION;
            case KeyEvent.VK_INVERTED_EXCLAMATION_MARK -> null;
            case KeyEvent.VK_LEFT_PARENTHESIS -> Key.LEFT_PARENTHESIS;
            case KeyEvent.VK_NUMBER_SIGN -> Key.HASH;
            case KeyEvent.VK_PLUS -> Key.PLUS;
            case KeyEvent.VK_RIGHT_PARENTHESIS -> Key.RIGHT_PARENTHESIS;
            case KeyEvent.VK_UNDERSCORE -> Key.UNDERSCORE;
            case KeyEvent.VK_WINDOWS -> Key.LEFT_SUPER;
            case KeyEvent.VK_CONTEXT_MENU -> Key.MENU;
            case KeyEvent.VK_FINAL -> null;
            case KeyEvent.VK_CONVERT -> null;
            case KeyEvent.VK_NONCONVERT -> null;
            case KeyEvent.VK_ACCEPT -> null;
            case KeyEvent.VK_MODECHANGE -> null;
            case KeyEvent.VK_KANA -> null;
            case KeyEvent.VK_KANJI -> null;
            case KeyEvent.VK_ALPHANUMERIC -> null;
            case KeyEvent.VK_KATAKANA -> null;
            case KeyEvent.VK_HIRAGANA -> null;
            case KeyEvent.VK_FULL_WIDTH -> null;
            case KeyEvent.VK_HALF_WIDTH -> null;
            case KeyEvent.VK_ROMAN_CHARACTERS -> null;
            case KeyEvent.VK_ALL_CANDIDATES -> null;
            case KeyEvent.VK_PREVIOUS_CANDIDATE -> null;
            case KeyEvent.VK_CODE_INPUT -> null;
            case KeyEvent.VK_JAPANESE_KATAKANA -> null;
            case KeyEvent.VK_JAPANESE_HIRAGANA -> null;
            case KeyEvent.VK_JAPANESE_ROMAN -> null;
            case KeyEvent.VK_KANA_LOCK -> null;
            case KeyEvent.VK_INPUT_METHOD_ON_OFF -> null;
            case KeyEvent.VK_CUT -> null;
            case KeyEvent.VK_COPY -> null;
            case KeyEvent.VK_PASTE -> null;
            case KeyEvent.VK_UNDO -> null;
            case KeyEvent.VK_AGAIN -> null;
            case KeyEvent.VK_FIND -> null;
            case KeyEvent.VK_PROPS -> null;
            case KeyEvent.VK_STOP -> null;
            case KeyEvent.VK_COMPOSE -> null;
            case KeyEvent.VK_ALT_GRAPH -> null;
            case KeyEvent.VK_BEGIN -> null;
            case KeyEvent.VK_UNDEFINED -> null;
            case KeyEvent.CHAR_UNDEFINED -> null;
            default -> null;
        };
        if (key == null) return null;
        return new net.lenni0451.rivet.input.keyboard.KeyEvent(key, mapModifiers(modifier));
    }

    public static int mapKey(final Key key) {
        return switch (key) {
            case SPACE -> KeyEvent.VK_SPACE;
            case APOSTROPHE -> KeyEvent.VK_QUOTE;
            case COMMA -> KeyEvent.VK_COMMA;
            case MINUS -> KeyEvent.VK_MINUS;
            case PERIOD -> KeyEvent.VK_PERIOD;
            case SLASH -> KeyEvent.VK_SLASH;
            case KB_0 -> KeyEvent.VK_0;
            case KB_1 -> KeyEvent.VK_1;
            case KB_2 -> KeyEvent.VK_2;
            case KB_3 -> KeyEvent.VK_3;
            case KB_4 -> KeyEvent.VK_4;
            case KB_5 -> KeyEvent.VK_5;
            case KB_6 -> KeyEvent.VK_6;
            case KB_7 -> KeyEvent.VK_7;
            case KB_8 -> KeyEvent.VK_8;
            case KB_9 -> KeyEvent.VK_9;
            case SEMICOLON -> KeyEvent.VK_SEMICOLON;
            case EQUAL -> KeyEvent.VK_EQUALS;
            case A -> KeyEvent.VK_A;
            case B -> KeyEvent.VK_B;
            case C -> KeyEvent.VK_C;
            case D -> KeyEvent.VK_D;
            case E -> KeyEvent.VK_E;
            case F -> KeyEvent.VK_F;
            case G -> KeyEvent.VK_G;
            case H -> KeyEvent.VK_H;
            case I -> KeyEvent.VK_I;
            case J -> KeyEvent.VK_J;
            case K -> KeyEvent.VK_K;
            case L -> KeyEvent.VK_L;
            case M -> KeyEvent.VK_M;
            case N -> KeyEvent.VK_N;
            case O -> KeyEvent.VK_O;
            case P -> KeyEvent.VK_P;
            case Q -> KeyEvent.VK_Q;
            case R -> KeyEvent.VK_R;
            case S -> KeyEvent.VK_S;
            case T -> KeyEvent.VK_T;
            case U -> KeyEvent.VK_U;
            case V -> KeyEvent.VK_V;
            case W -> KeyEvent.VK_W;
            case X -> KeyEvent.VK_X;
            case Y -> KeyEvent.VK_Y;
            case Z -> KeyEvent.VK_Z;
            case LEFT_BRACKET -> KeyEvent.VK_OPEN_BRACKET;
            case BACKSLASH -> KeyEvent.VK_BACK_SLASH;
            case RIGHT_BRACKET -> KeyEvent.VK_CLOSE_BRACKET;
            case GRAVE_ACCENT -> KeyEvent.VK_BACK_QUOTE;
            case ESCAPE -> KeyEvent.VK_ESCAPE;
            case ENTER -> KeyEvent.VK_ENTER;
            case TAB -> KeyEvent.VK_TAB;
            case BACKSPACE -> KeyEvent.VK_BACK_SPACE;
            case INSERT -> KeyEvent.VK_INSERT;
            case DELETE -> KeyEvent.VK_DELETE;
            case RIGHT -> KeyEvent.VK_RIGHT;
            case LEFT -> KeyEvent.VK_LEFT;
            case DOWN -> KeyEvent.VK_DOWN;
            case UP -> KeyEvent.VK_UP;
            case PAGE_UP -> KeyEvent.VK_PAGE_UP;
            case PAGE_DOWN -> KeyEvent.VK_PAGE_DOWN;
            case HOME -> KeyEvent.VK_HOME;
            case END -> KeyEvent.VK_END;
            case CAPS_LOCK -> KeyEvent.VK_CAPS_LOCK;
            case SCROLL_LOCK -> KeyEvent.VK_SCROLL_LOCK;
            case NUM_LOCK -> KeyEvent.VK_NUM_LOCK;
            case PRINT_SCREEN -> KeyEvent.VK_PRINTSCREEN;
            case PAUSE -> KeyEvent.VK_PAUSE;
            case F1 -> KeyEvent.VK_F1;
            case F2 -> KeyEvent.VK_F2;
            case F3 -> KeyEvent.VK_F3;
            case F4 -> KeyEvent.VK_F4;
            case F5 -> KeyEvent.VK_F5;
            case F6 -> KeyEvent.VK_F6;
            case F7 -> KeyEvent.VK_F7;
            case F8 -> KeyEvent.VK_F8;
            case F9 -> KeyEvent.VK_F9;
            case F10 -> KeyEvent.VK_F10;
            case F11 -> KeyEvent.VK_F11;
            case F12 -> KeyEvent.VK_F12;
            case F13 -> KeyEvent.VK_F13;
            case F14 -> KeyEvent.VK_F14;
            case F15 -> KeyEvent.VK_F15;
            case F16 -> KeyEvent.VK_F16;
            case F17 -> KeyEvent.VK_F17;
            case F18 -> KeyEvent.VK_F18;
            case F19 -> KeyEvent.VK_F19;
            case F20 -> KeyEvent.VK_F20;
            case F21 -> KeyEvent.VK_F21;
            case F22 -> KeyEvent.VK_F22;
            case F23 -> KeyEvent.VK_F23;
            case F24 -> KeyEvent.VK_F24;
            case KP_0 -> KeyEvent.VK_NUMPAD0;
            case KP_1 -> KeyEvent.VK_NUMPAD1;
            case KP_2 -> KeyEvent.VK_NUMPAD2;
            case KP_3 -> KeyEvent.VK_NUMPAD3;
            case KP_4 -> KeyEvent.VK_NUMPAD4;
            case KP_5 -> KeyEvent.VK_NUMPAD5;
            case KP_6 -> KeyEvent.VK_NUMPAD6;
            case KP_7 -> KeyEvent.VK_NUMPAD7;
            case KP_8 -> KeyEvent.VK_NUMPAD8;
            case KP_9 -> KeyEvent.VK_NUMPAD9;
            case KP_DECIMAL -> KeyEvent.VK_DECIMAL;
            case KP_DIVIDE -> KeyEvent.VK_DIVIDE;
            case KP_MULTIPLY -> KeyEvent.VK_MULTIPLY;
            case KP_SUBTRACT -> KeyEvent.VK_SUBTRACT;
            case KP_ADD -> KeyEvent.VK_ADD;
            case KP_ENTER -> KeyEvent.VK_ENTER;
            case KP_EQUAL -> KeyEvent.VK_EQUALS;
            case LEFT_SHIFT -> KeyEvent.VK_SHIFT;
            case LEFT_CONTROL -> KeyEvent.VK_CONTROL;
            case LEFT_ALT -> KeyEvent.VK_ALT;
            case LEFT_SUPER -> KeyEvent.VK_WINDOWS;
            case RIGHT_SHIFT -> KeyEvent.VK_SHIFT;
            case RIGHT_CONTROL -> KeyEvent.VK_CONTROL;
            case RIGHT_ALT -> KeyEvent.VK_ALT;
            case RIGHT_SUPER -> KeyEvent.VK_WINDOWS;
            case MENU -> KeyEvent.VK_CONTEXT_MENU;
            case PLUS -> KeyEvent.VK_PLUS;
            case ASTERISK -> KeyEvent.VK_ASTERISK;
            case HASH -> KeyEvent.VK_NUMBER_SIGN;
            case LESS -> KeyEvent.VK_LESS;
            case GREATER -> KeyEvent.VK_GREATER;
            case QUESTION -> KeyEvent.VK_UNDEFINED;
            case AT -> KeyEvent.VK_AT;
            case CARET -> KeyEvent.VK_CIRCUMFLEX;
            case UNDERSCORE -> KeyEvent.VK_UNDERSCORE;
            case LEFT_PARENTHESIS -> KeyEvent.VK_LEFT_PARENTHESIS;
            case RIGHT_PARENTHESIS -> KeyEvent.VK_RIGHT_PARENTHESIS;
            case LEFT_BRACE -> KeyEvent.VK_BRACELEFT;
            case RIGHT_BRACE -> KeyEvent.VK_BRACERIGHT;
            case PIPE -> KeyEvent.VK_UNDEFINED;
            case TILDE -> KeyEvent.VK_UNDEFINED;
            case COLON -> KeyEvent.VK_COLON;
            case EXCLAMATION -> KeyEvent.VK_EXCLAMATION_MARK;
            case DOUBLE_QUOTE -> KeyEvent.VK_QUOTEDBL;
            case DOLLAR -> KeyEvent.VK_DOLLAR;
            case PERCENT -> KeyEvent.VK_UNDEFINED;
            case AMPERSAND -> KeyEvent.VK_AMPERSAND;
        };
    }

    @Nullable
    public static MouseButtonEvent mapMouseButton(final float x, final float y, final int button, final int modifier) {
        MouseButton mouseButton = switch (button) {
            case MouseEvent.BUTTON1 -> MouseButton.LEFT;
            case MouseEvent.BUTTON3 -> MouseButton.RIGHT;
            case MouseEvent.BUTTON2 -> MouseButton.MIDDLE;
            default -> null;
        };
        if (mouseButton == null) return null;
        return new MouseButtonEvent(x, y, mouseButton, mapModifiers(modifier), Set.of());
    }

    private static Set<ModifierKey> mapModifiers(final int modifier) {
        Set<ModifierKey> modifiers = EnumSet.noneOf(ModifierKey.class);
        if ((modifier & KeyEvent.SHIFT_DOWN_MASK) != 0) modifiers.add(ModifierKey.SHIFT);
        if ((modifier & KeyEvent.CTRL_DOWN_MASK) != 0) modifiers.add(ModifierKey.CONTROL);
        if ((modifier & KeyEvent.ALT_DOWN_MASK) != 0) modifiers.add(ModifierKey.ALT);
        if ((modifier & KeyEvent.META_DOWN_MASK) != 0) modifiers.add(ModifierKey.SUPER);
        return modifiers;
    }


}
