package net.lenni0451.rivet.backend.thingl.utils;

import lombok.experimental.UtilityClass;
import net.lenni0451.rivet.input.keyboard.Key;
import net.lenni0451.rivet.input.keyboard.KeyEvent;
import net.lenni0451.rivet.input.keyboard.ModifierKey;
import net.lenni0451.rivet.input.mouse.MouseButton;
import net.lenni0451.rivet.input.mouse.MouseButtonEvent;
import org.lwjgl.sdl.SDLKeycode;
import org.lwjgl.sdl.SDLMouse;

import javax.annotation.Nullable;
import java.util.EnumSet;
import java.util.Set;

@UtilityClass
public class SDLMapper {

    @Nullable
    public static KeyEvent mapKeycode(final int keycode, final int modifier) {
        Key key = switch (keycode) {
            case SDLKeycode.SDLK_UNKNOWN -> null;
            case SDLKeycode.SDLK_RETURN -> Key.ENTER;
            case SDLKeycode.SDLK_ESCAPE -> Key.ESCAPE;
            case SDLKeycode.SDLK_BACKSPACE -> Key.BACKSPACE;
            case SDLKeycode.SDLK_TAB -> Key.TAB;
            case SDLKeycode.SDLK_SPACE -> Key.SPACE;
            case SDLKeycode.SDLK_EXCLAIM -> Key.EXCLAMATION;
            case SDLKeycode.SDLK_DBLAPOSTROPHE -> Key.DOUBLE_QUOTE;
            case SDLKeycode.SDLK_HASH -> Key.HASH;
            case SDLKeycode.SDLK_DOLLAR -> Key.DOLLAR;
            case SDLKeycode.SDLK_PERCENT -> Key.PERCENT;
            case SDLKeycode.SDLK_AMPERSAND -> Key.AMPERSAND;
            case SDLKeycode.SDLK_APOSTROPHE -> Key.APOSTROPHE;
            case SDLKeycode.SDLK_LEFTPAREN -> Key.LEFT_PARENTHESIS;
            case SDLKeycode.SDLK_RIGHTPAREN -> Key.RIGHT_PARENTHESIS;
            case SDLKeycode.SDLK_ASTERISK -> Key.ASTERISK;
            case SDLKeycode.SDLK_PLUS -> Key.PLUS;
            case SDLKeycode.SDLK_COMMA -> Key.COMMA;
            case SDLKeycode.SDLK_MINUS -> Key.MINUS;
            case SDLKeycode.SDLK_PERIOD -> Key.PERIOD;
            case SDLKeycode.SDLK_SLASH -> Key.SLASH;
            case SDLKeycode.SDLK_0 -> Key.KB_0;
            case SDLKeycode.SDLK_1 -> Key.KB_1;
            case SDLKeycode.SDLK_2 -> Key.KB_2;
            case SDLKeycode.SDLK_3 -> Key.KB_3;
            case SDLKeycode.SDLK_4 -> Key.KB_4;
            case SDLKeycode.SDLK_5 -> Key.KB_5;
            case SDLKeycode.SDLK_6 -> Key.KB_6;
            case SDLKeycode.SDLK_7 -> Key.KB_7;
            case SDLKeycode.SDLK_8 -> Key.KB_8;
            case SDLKeycode.SDLK_9 -> Key.KB_9;
            case SDLKeycode.SDLK_COLON -> Key.COLON;
            case SDLKeycode.SDLK_SEMICOLON -> Key.SEMICOLON;
            case SDLKeycode.SDLK_LESS -> Key.LESS;
            case SDLKeycode.SDLK_EQUALS -> Key.EQUAL;
            case SDLKeycode.SDLK_GREATER -> Key.GREATER;
            case SDLKeycode.SDLK_QUESTION -> Key.QUESTION;
            case SDLKeycode.SDLK_AT -> Key.AT;
            case SDLKeycode.SDLK_LEFTBRACKET -> Key.LEFT_BRACKET;
            case SDLKeycode.SDLK_BACKSLASH -> Key.BACKSLASH;
            case SDLKeycode.SDLK_RIGHTBRACKET -> Key.RIGHT_BRACKET;
            case SDLKeycode.SDLK_CARET -> Key.CARET;
            case SDLKeycode.SDLK_UNDERSCORE -> Key.UNDERSCORE;
            case SDLKeycode.SDLK_GRAVE -> Key.GRAVE_ACCENT;
            case SDLKeycode.SDLK_A -> Key.A;
            case SDLKeycode.SDLK_B -> Key.B;
            case SDLKeycode.SDLK_C -> Key.C;
            case SDLKeycode.SDLK_D -> Key.D;
            case SDLKeycode.SDLK_E -> Key.E;
            case SDLKeycode.SDLK_F -> Key.F;
            case SDLKeycode.SDLK_G -> Key.G;
            case SDLKeycode.SDLK_H -> Key.H;
            case SDLKeycode.SDLK_I -> Key.I;
            case SDLKeycode.SDLK_J -> Key.J;
            case SDLKeycode.SDLK_K -> Key.K;
            case SDLKeycode.SDLK_L -> Key.L;
            case SDLKeycode.SDLK_M -> Key.M;
            case SDLKeycode.SDLK_N -> Key.N;
            case SDLKeycode.SDLK_O -> Key.O;
            case SDLKeycode.SDLK_P -> Key.P;
            case SDLKeycode.SDLK_Q -> Key.Q;
            case SDLKeycode.SDLK_R -> Key.R;
            case SDLKeycode.SDLK_S -> Key.S;
            case SDLKeycode.SDLK_T -> Key.T;
            case SDLKeycode.SDLK_U -> Key.U;
            case SDLKeycode.SDLK_V -> Key.V;
            case SDLKeycode.SDLK_W -> Key.W;
            case SDLKeycode.SDLK_X -> Key.X;
            case SDLKeycode.SDLK_Y -> Key.Y;
            case SDLKeycode.SDLK_Z -> Key.Z;
            case SDLKeycode.SDLK_LEFTBRACE -> Key.LEFT_BRACE;
            case SDLKeycode.SDLK_PIPE -> Key.PIPE;
            case SDLKeycode.SDLK_RIGHTBRACE -> Key.RIGHT_BRACE;
            case SDLKeycode.SDLK_TILDE -> Key.TILDE;
            case SDLKeycode.SDLK_DELETE -> Key.DELETE;
            case SDLKeycode.SDLK_PLUSMINUS -> null;
            case SDLKeycode.SDLK_CAPSLOCK -> Key.CAPS_LOCK;
            case SDLKeycode.SDLK_F1 -> Key.F1;
            case SDLKeycode.SDLK_F2 -> Key.F2;
            case SDLKeycode.SDLK_F3 -> Key.F3;
            case SDLKeycode.SDLK_F4 -> Key.F4;
            case SDLKeycode.SDLK_F5 -> Key.F5;
            case SDLKeycode.SDLK_F6 -> Key.F6;
            case SDLKeycode.SDLK_F7 -> Key.F7;
            case SDLKeycode.SDLK_F8 -> Key.F8;
            case SDLKeycode.SDLK_F9 -> Key.F9;
            case SDLKeycode.SDLK_F10 -> Key.F10;
            case SDLKeycode.SDLK_F11 -> Key.F11;
            case SDLKeycode.SDLK_F12 -> Key.F12;
            case SDLKeycode.SDLK_PRINTSCREEN -> Key.PRINT_SCREEN;
            case SDLKeycode.SDLK_SCROLLLOCK -> Key.SCROLL_LOCK;
            case SDLKeycode.SDLK_PAUSE -> Key.PAUSE;
            case SDLKeycode.SDLK_INSERT -> Key.INSERT;
            case SDLKeycode.SDLK_HOME -> Key.HOME;
            case SDLKeycode.SDLK_PAGEUP -> Key.PAGE_UP;
            case SDLKeycode.SDLK_END -> Key.END;
            case SDLKeycode.SDLK_PAGEDOWN -> Key.PAGE_DOWN;
            case SDLKeycode.SDLK_RIGHT -> Key.RIGHT;
            case SDLKeycode.SDLK_LEFT -> Key.LEFT;
            case SDLKeycode.SDLK_DOWN -> Key.DOWN;
            case SDLKeycode.SDLK_UP -> Key.UP;
            case SDLKeycode.SDLK_NUMLOCKCLEAR -> Key.NUM_LOCK;
            case SDLKeycode.SDLK_KP_DIVIDE -> Key.KP_DIVIDE;
            case SDLKeycode.SDLK_KP_MULTIPLY -> Key.KP_MULTIPLY;
            case SDLKeycode.SDLK_KP_MINUS -> Key.KP_SUBTRACT;
            case SDLKeycode.SDLK_KP_PLUS -> Key.KP_ADD;
            case SDLKeycode.SDLK_KP_ENTER -> Key.KP_ENTER;
            case SDLKeycode.SDLK_KP_1 -> Key.KP_1;
            case SDLKeycode.SDLK_KP_2 -> Key.KP_2;
            case SDLKeycode.SDLK_KP_3 -> Key.KP_3;
            case SDLKeycode.SDLK_KP_4 -> Key.KP_4;
            case SDLKeycode.SDLK_KP_5 -> Key.KP_5;
            case SDLKeycode.SDLK_KP_6 -> Key.KP_6;
            case SDLKeycode.SDLK_KP_7 -> Key.KP_7;
            case SDLKeycode.SDLK_KP_8 -> Key.KP_8;
            case SDLKeycode.SDLK_KP_9 -> Key.KP_9;
            case SDLKeycode.SDLK_KP_0 -> Key.KP_0;
            case SDLKeycode.SDLK_KP_PERIOD -> Key.KP_DECIMAL;
            case SDLKeycode.SDLK_APPLICATION -> Key.MENU;
            case SDLKeycode.SDLK_POWER -> null;
            case SDLKeycode.SDLK_KP_EQUALS -> Key.KP_EQUAL;
            case SDLKeycode.SDLK_F13 -> Key.F13;
            case SDLKeycode.SDLK_F14 -> Key.F14;
            case SDLKeycode.SDLK_F15 -> Key.F15;
            case SDLKeycode.SDLK_F16 -> Key.F16;
            case SDLKeycode.SDLK_F17 -> Key.F17;
            case SDLKeycode.SDLK_F18 -> Key.F18;
            case SDLKeycode.SDLK_F19 -> Key.F19;
            case SDLKeycode.SDLK_F20 -> Key.F20;
            case SDLKeycode.SDLK_F21 -> Key.F21;
            case SDLKeycode.SDLK_F22 -> Key.F22;
            case SDLKeycode.SDLK_F23 -> Key.F23;
            case SDLKeycode.SDLK_F24 -> Key.F24;
            case SDLKeycode.SDLK_EXECUTE -> null;
            case SDLKeycode.SDLK_HELP -> null;
            case SDLKeycode.SDLK_MENU -> Key.MENU;
            case SDLKeycode.SDLK_SELECT -> null;
            case SDLKeycode.SDLK_STOP -> null;
            case SDLKeycode.SDLK_AGAIN -> null;
            case SDLKeycode.SDLK_UNDO -> null;
            case SDLKeycode.SDLK_CUT -> null;
            case SDLKeycode.SDLK_COPY -> null;
            case SDLKeycode.SDLK_PASTE -> null;
            case SDLKeycode.SDLK_FIND -> null;
            case SDLKeycode.SDLK_MUTE -> null;
            case SDLKeycode.SDLK_VOLUMEUP -> null;
            case SDLKeycode.SDLK_VOLUMEDOWN -> null;
            case SDLKeycode.SDLK_KP_COMMA -> null;
            case SDLKeycode.SDLK_KP_EQUALSAS400 -> null;
            case SDLKeycode.SDLK_ALTERASE -> null;
            case SDLKeycode.SDLK_SYSREQ -> null;
            case SDLKeycode.SDLK_CANCEL -> null;
            case SDLKeycode.SDLK_CLEAR -> null;
            case SDLKeycode.SDLK_PRIOR -> null;
            case SDLKeycode.SDLK_RETURN2 -> null;
            case SDLKeycode.SDLK_SEPARATOR -> null;
            case SDLKeycode.SDLK_OUT -> null;
            case SDLKeycode.SDLK_OPER -> null;
            case SDLKeycode.SDLK_CLEARAGAIN -> null;
            case SDLKeycode.SDLK_CRSEL -> null;
            case SDLKeycode.SDLK_EXSEL -> null;
            case SDLKeycode.SDLK_KP_00 -> null;
            case SDLKeycode.SDLK_KP_000 -> null;
            case SDLKeycode.SDLK_THOUSANDSSEPARATOR -> null;
            case SDLKeycode.SDLK_DECIMALSEPARATOR -> null;
            case SDLKeycode.SDLK_CURRENCYUNIT -> null;
            case SDLKeycode.SDLK_CURRENCYSUBUNIT -> null;
            case SDLKeycode.SDLK_KP_LEFTPAREN -> null;
            case SDLKeycode.SDLK_KP_RIGHTPAREN -> null;
            case SDLKeycode.SDLK_KP_LEFTBRACE -> null;
            case SDLKeycode.SDLK_KP_RIGHTBRACE -> null;
            case SDLKeycode.SDLK_KP_TAB -> null;
            case SDLKeycode.SDLK_KP_BACKSPACE -> null;
            case SDLKeycode.SDLK_KP_A -> null;
            case SDLKeycode.SDLK_KP_B -> null;
            case SDLKeycode.SDLK_KP_C -> null;
            case SDLKeycode.SDLK_KP_D -> null;
            case SDLKeycode.SDLK_KP_E -> null;
            case SDLKeycode.SDLK_KP_F -> null;
            case SDLKeycode.SDLK_KP_XOR -> null;
            case SDLKeycode.SDLK_KP_POWER -> null;
            case SDLKeycode.SDLK_KP_PERCENT -> null;
            case SDLKeycode.SDLK_KP_LESS -> null;
            case SDLKeycode.SDLK_KP_GREATER -> null;
            case SDLKeycode.SDLK_KP_AMPERSAND -> null;
            case SDLKeycode.SDLK_KP_DBLAMPERSAND -> null;
            case SDLKeycode.SDLK_KP_VERTICALBAR -> null;
            case SDLKeycode.SDLK_KP_DBLVERTICALBAR -> null;
            case SDLKeycode.SDLK_KP_COLON -> null;
            case SDLKeycode.SDLK_KP_HASH -> null;
            case SDLKeycode.SDLK_KP_SPACE -> null;
            case SDLKeycode.SDLK_KP_AT -> null;
            case SDLKeycode.SDLK_KP_EXCLAM -> null;
            case SDLKeycode.SDLK_KP_MEMSTORE -> null;
            case SDLKeycode.SDLK_KP_MEMRECALL -> null;
            case SDLKeycode.SDLK_KP_MEMCLEAR -> null;
            case SDLKeycode.SDLK_KP_MEMADD -> null;
            case SDLKeycode.SDLK_KP_MEMSUBTRACT -> null;
            case SDLKeycode.SDLK_KP_MEMMULTIPLY -> null;
            case SDLKeycode.SDLK_KP_MEMDIVIDE -> null;
            case SDLKeycode.SDLK_KP_PLUSMINUS -> null;
            case SDLKeycode.SDLK_KP_CLEAR -> null;
            case SDLKeycode.SDLK_KP_CLEARENTRY -> null;
            case SDLKeycode.SDLK_KP_BINARY -> null;
            case SDLKeycode.SDLK_KP_OCTAL -> null;
            case SDLKeycode.SDLK_KP_DECIMAL -> null;
            case SDLKeycode.SDLK_KP_HEXADECIMAL -> null;
            case SDLKeycode.SDLK_LCTRL -> Key.LEFT_CONTROL;
            case SDLKeycode.SDLK_LSHIFT -> Key.LEFT_SHIFT;
            case SDLKeycode.SDLK_LALT -> Key.LEFT_ALT;
            case SDLKeycode.SDLK_LGUI -> Key.LEFT_SUPER;
            case SDLKeycode.SDLK_RCTRL -> Key.RIGHT_CONTROL;
            case SDLKeycode.SDLK_RSHIFT -> Key.RIGHT_SHIFT;
            case SDLKeycode.SDLK_RALT -> Key.RIGHT_ALT;
            case SDLKeycode.SDLK_RGUI -> Key.RIGHT_SUPER;
            case SDLKeycode.SDLK_MODE -> null;
            case SDLKeycode.SDLK_SLEEP -> null;
            case SDLKeycode.SDLK_WAKE -> null;
            case SDLKeycode.SDLK_CHANNEL_INCREMENT -> null;
            case SDLKeycode.SDLK_CHANNEL_DECREMENT -> null;
            case SDLKeycode.SDLK_MEDIA_PLAY -> null;
            case SDLKeycode.SDLK_MEDIA_PAUSE -> null;
            case SDLKeycode.SDLK_MEDIA_RECORD -> null;
            case SDLKeycode.SDLK_MEDIA_FAST_FORWARD -> null;
            case SDLKeycode.SDLK_MEDIA_REWIND -> null;
            case SDLKeycode.SDLK_MEDIA_NEXT_TRACK -> null;
            case SDLKeycode.SDLK_MEDIA_PREVIOUS_TRACK -> null;
            case SDLKeycode.SDLK_MEDIA_STOP -> null;
            case SDLKeycode.SDLK_MEDIA_EJECT -> null;
            case SDLKeycode.SDLK_MEDIA_PLAY_PAUSE -> null;
            case SDLKeycode.SDLK_MEDIA_SELECT -> null;
            case SDLKeycode.SDLK_AC_NEW -> null;
            case SDLKeycode.SDLK_AC_OPEN -> null;
            case SDLKeycode.SDLK_AC_CLOSE -> null;
            case SDLKeycode.SDLK_AC_EXIT -> null;
            case SDLKeycode.SDLK_AC_SAVE -> null;
            case SDLKeycode.SDLK_AC_PRINT -> null;
            case SDLKeycode.SDLK_AC_PROPERTIES -> null;
            case SDLKeycode.SDLK_AC_SEARCH -> null;
            case SDLKeycode.SDLK_AC_HOME -> null;
            case SDLKeycode.SDLK_AC_BACK -> null;
            case SDLKeycode.SDLK_AC_FORWARD -> null;
            case SDLKeycode.SDLK_AC_STOP -> null;
            case SDLKeycode.SDLK_AC_REFRESH -> null;
            case SDLKeycode.SDLK_AC_BOOKMARKS -> null;
            case SDLKeycode.SDLK_SOFTLEFT -> null;
            case SDLKeycode.SDLK_SOFTRIGHT -> null;
            case SDLKeycode.SDLK_CALL -> null;
            case SDLKeycode.SDLK_ENDCALL -> null;
            case SDLKeycode.SDLK_LEFT_TAB -> null;
            case SDLKeycode.SDLK_LEVEL5_SHIFT -> null;
            case SDLKeycode.SDLK_MULTI_KEY_COMPOSE -> null;
            case SDLKeycode.SDLK_LMETA -> null;
            case SDLKeycode.SDLK_RMETA -> null;
            case SDLKeycode.SDLK_LHYPER -> null;
            case SDLKeycode.SDLK_RHYPER -> null;
            default -> null;
        };
        if (key == null) return null;
        return new KeyEvent(key, mapModifiers(modifier));
    }

    public static int mapKey(final Key key) {
        return switch (key) {
            case SPACE -> SDLKeycode.SDLK_SPACE;
            case APOSTROPHE -> SDLKeycode.SDLK_APOSTROPHE;
            case COMMA -> SDLKeycode.SDLK_COMMA;
            case MINUS -> SDLKeycode.SDLK_MINUS;
            case PERIOD -> SDLKeycode.SDLK_PERIOD;
            case SLASH -> SDLKeycode.SDLK_SLASH;
            case KB_0 -> SDLKeycode.SDLK_0;
            case KB_1 -> SDLKeycode.SDLK_1;
            case KB_2 -> SDLKeycode.SDLK_2;
            case KB_3 -> SDLKeycode.SDLK_3;
            case KB_4 -> SDLKeycode.SDLK_4;
            case KB_5 -> SDLKeycode.SDLK_5;
            case KB_6 -> SDLKeycode.SDLK_6;
            case KB_7 -> SDLKeycode.SDLK_7;
            case KB_8 -> SDLKeycode.SDLK_8;
            case KB_9 -> SDLKeycode.SDLK_9;
            case SEMICOLON -> SDLKeycode.SDLK_SEMICOLON;
            case EQUAL -> SDLKeycode.SDLK_EQUALS;
            case A -> SDLKeycode.SDLK_A;
            case B -> SDLKeycode.SDLK_B;
            case C -> SDLKeycode.SDLK_C;
            case D -> SDLKeycode.SDLK_D;
            case E -> SDLKeycode.SDLK_E;
            case F -> SDLKeycode.SDLK_F;
            case G -> SDLKeycode.SDLK_G;
            case H -> SDLKeycode.SDLK_H;
            case I -> SDLKeycode.SDLK_I;
            case J -> SDLKeycode.SDLK_J;
            case K -> SDLKeycode.SDLK_K;
            case L -> SDLKeycode.SDLK_L;
            case M -> SDLKeycode.SDLK_M;
            case N -> SDLKeycode.SDLK_N;
            case O -> SDLKeycode.SDLK_O;
            case P -> SDLKeycode.SDLK_P;
            case Q -> SDLKeycode.SDLK_Q;
            case R -> SDLKeycode.SDLK_R;
            case S -> SDLKeycode.SDLK_S;
            case T -> SDLKeycode.SDLK_T;
            case U -> SDLKeycode.SDLK_U;
            case V -> SDLKeycode.SDLK_V;
            case W -> SDLKeycode.SDLK_W;
            case X -> SDLKeycode.SDLK_X;
            case Y -> SDLKeycode.SDLK_Y;
            case Z -> SDLKeycode.SDLK_Z;
            case LEFT_BRACKET -> SDLKeycode.SDLK_LEFTBRACKET;
            case BACKSLASH -> SDLKeycode.SDLK_BACKSLASH;
            case RIGHT_BRACKET -> SDLKeycode.SDLK_RIGHTBRACKET;
            case GRAVE_ACCENT -> SDLKeycode.SDLK_GRAVE;
            case ESCAPE -> SDLKeycode.SDLK_ESCAPE;
            case ENTER -> SDLKeycode.SDLK_RETURN;
            case TAB -> SDLKeycode.SDLK_TAB;
            case BACKSPACE -> SDLKeycode.SDLK_BACKSPACE;
            case INSERT -> SDLKeycode.SDLK_INSERT;
            case DELETE -> SDLKeycode.SDLK_DELETE;
            case RIGHT -> SDLKeycode.SDLK_RIGHT;
            case LEFT -> SDLKeycode.SDLK_LEFT;
            case DOWN -> SDLKeycode.SDLK_DOWN;
            case UP -> SDLKeycode.SDLK_UP;
            case PAGE_UP -> SDLKeycode.SDLK_PAGEUP;
            case PAGE_DOWN -> SDLKeycode.SDLK_PAGEDOWN;
            case HOME -> SDLKeycode.SDLK_HOME;
            case END -> SDLKeycode.SDLK_END;
            case CAPS_LOCK -> SDLKeycode.SDLK_CAPSLOCK;
            case SCROLL_LOCK -> SDLKeycode.SDLK_SCROLLLOCK;
            case NUM_LOCK -> SDLKeycode.SDLK_NUMLOCKCLEAR;
            case PRINT_SCREEN -> SDLKeycode.SDLK_PRINTSCREEN;
            case PAUSE -> SDLKeycode.SDLK_PAUSE;
            case F1 -> SDLKeycode.SDLK_F1;
            case F2 -> SDLKeycode.SDLK_F2;
            case F3 -> SDLKeycode.SDLK_F3;
            case F4 -> SDLKeycode.SDLK_F4;
            case F5 -> SDLKeycode.SDLK_F5;
            case F6 -> SDLKeycode.SDLK_F6;
            case F7 -> SDLKeycode.SDLK_F7;
            case F8 -> SDLKeycode.SDLK_F8;
            case F9 -> SDLKeycode.SDLK_F9;
            case F10 -> SDLKeycode.SDLK_F10;
            case F11 -> SDLKeycode.SDLK_F11;
            case F12 -> SDLKeycode.SDLK_F12;
            case F13 -> SDLKeycode.SDLK_F13;
            case F14 -> SDLKeycode.SDLK_F14;
            case F15 -> SDLKeycode.SDLK_F15;
            case F16 -> SDLKeycode.SDLK_F16;
            case F17 -> SDLKeycode.SDLK_F17;
            case F18 -> SDLKeycode.SDLK_F18;
            case F19 -> SDLKeycode.SDLK_F19;
            case F20 -> SDLKeycode.SDLK_F20;
            case F21 -> SDLKeycode.SDLK_F21;
            case F22 -> SDLKeycode.SDLK_F22;
            case F23 -> SDLKeycode.SDLK_F23;
            case F24 -> SDLKeycode.SDLK_F24;
            case KP_0 -> SDLKeycode.SDLK_KP_0;
            case KP_1 -> SDLKeycode.SDLK_KP_1;
            case KP_2 -> SDLKeycode.SDLK_KP_2;
            case KP_3 -> SDLKeycode.SDLK_KP_3;
            case KP_4 -> SDLKeycode.SDLK_KP_4;
            case KP_5 -> SDLKeycode.SDLK_KP_5;
            case KP_6 -> SDLKeycode.SDLK_KP_6;
            case KP_7 -> SDLKeycode.SDLK_KP_7;
            case KP_8 -> SDLKeycode.SDLK_KP_8;
            case KP_9 -> SDLKeycode.SDLK_KP_9;
            case KP_DECIMAL -> SDLKeycode.SDLK_KP_PERIOD;
            case KP_DIVIDE -> SDLKeycode.SDLK_KP_DIVIDE;
            case KP_MULTIPLY -> SDLKeycode.SDLK_KP_MULTIPLY;
            case KP_SUBTRACT -> SDLKeycode.SDLK_KP_MINUS;
            case KP_ADD -> SDLKeycode.SDLK_KP_PLUS;
            case KP_ENTER -> SDLKeycode.SDLK_KP_ENTER;
            case KP_EQUAL -> SDLKeycode.SDLK_KP_EQUALS;
            case LEFT_SHIFT -> SDLKeycode.SDLK_LSHIFT;
            case LEFT_CONTROL -> SDLKeycode.SDLK_LCTRL;
            case LEFT_ALT -> SDLKeycode.SDLK_LALT;
            case LEFT_SUPER -> SDLKeycode.SDLK_LGUI;
            case RIGHT_SHIFT -> SDLKeycode.SDLK_RSHIFT;
            case RIGHT_CONTROL -> SDLKeycode.SDLK_RCTRL;
            case RIGHT_ALT -> SDLKeycode.SDLK_RALT;
            case RIGHT_SUPER -> SDLKeycode.SDLK_RGUI;
            case MENU -> SDLKeycode.SDLK_MENU; // Note: mapKeycode also maps SDLK_APPLICATION to Key.MENU.
            case PLUS -> SDLKeycode.SDLK_PLUS;
            case ASTERISK -> SDLKeycode.SDLK_ASTERISK;
            case HASH -> SDLKeycode.SDLK_HASH;
            case LESS -> SDLKeycode.SDLK_LESS;
            case GREATER -> SDLKeycode.SDLK_GREATER;
            case QUESTION -> SDLKeycode.SDLK_QUESTION;
            case AT -> SDLKeycode.SDLK_AT;
            case CARET -> SDLKeycode.SDLK_CARET;
            case UNDERSCORE -> SDLKeycode.SDLK_UNDERSCORE;
            case LEFT_PARENTHESIS -> SDLKeycode.SDLK_LEFTPAREN;
            case RIGHT_PARENTHESIS -> SDLKeycode.SDLK_RIGHTPAREN;
            case LEFT_BRACE -> SDLKeycode.SDLK_LEFTBRACE;
            case RIGHT_BRACE -> SDLKeycode.SDLK_RIGHTBRACE;
            case PIPE -> SDLKeycode.SDLK_PIPE;
            case TILDE -> SDLKeycode.SDLK_TILDE;
            case COLON -> SDLKeycode.SDLK_COLON;
            case EXCLAMATION -> SDLKeycode.SDLK_EXCLAIM;
            case DOUBLE_QUOTE -> SDLKeycode.SDLK_DBLAPOSTROPHE;
            case DOLLAR -> SDLKeycode.SDLK_DOLLAR;
            case PERCENT -> SDLKeycode.SDLK_PERCENT;
            case AMPERSAND -> SDLKeycode.SDLK_AMPERSAND;
        };
    }

    @Nullable
    public static MouseButtonEvent mapMouseButton(final float x, final float y, final int button, final int modifier) {
        MouseButton mouseButton = switch (button) {
            case SDLMouse.SDL_BUTTON_LEFT -> MouseButton.LEFT;
            case SDLMouse.SDL_BUTTON_RIGHT -> MouseButton.RIGHT;
            case SDLMouse.SDL_BUTTON_MIDDLE -> MouseButton.MIDDLE;
            default -> null;
        };
        if (mouseButton == null) return null;
        return new MouseButtonEvent(x, y, mouseButton, mapModifiers(modifier), Set.of());
    }

    private static Set<ModifierKey> mapModifiers(final int modifier) {
        Set<ModifierKey> modifiers = EnumSet.noneOf(ModifierKey.class);
        if ((modifier & SDLKeycode.SDL_KMOD_SHIFT) != 0) modifiers.add(ModifierKey.SHIFT);
        if ((modifier & SDLKeycode.SDL_KMOD_CTRL) != 0) modifiers.add(ModifierKey.CONTROL);
        if ((modifier & SDLKeycode.SDL_KMOD_ALT) != 0) modifiers.add(ModifierKey.ALT);
        if ((modifier & SDLKeycode.SDL_KMOD_GUI) != 0) modifiers.add(ModifierKey.SUPER);
        return modifiers;
    }

}
